# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/link_queue_main.dir/_3_stack_and_queue/queue/LinkQueueMain.c.o: ../_3_stack_and_queue/queue/LinkQueue.h
CMakeFiles/link_queue_main.dir/_3_stack_and_queue/queue/LinkQueueMain.c.o: ../_3_stack_and_queue/queue/LinkQueueImpl.h
CMakeFiles/link_queue_main.dir/_3_stack_and_queue/queue/LinkQueueMain.c.o: ../_3_stack_and_queue/queue/LinkQueueMain.c

