# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: ../_5_tree/BiTree.h
CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: ../_5_tree/BiTreeImpl.h
CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: ../_5_tree/BiTreeQueueImpl.h
CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: ../_5_tree/BiTreeStackImpl.h
CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: ../_5_tree/_ch5_se3_8.c
CMakeFiles/ch5_s3_8.dir/_5_tree/_ch5_se3_8.c.o: /usr/include/memory.h

