# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch5_s4_12.dir/_5_tree/_ch5_se4_12.c.o: ../_5_tree/BCTree.h
CMakeFiles/ch5_s4_12.dir/_5_tree/_ch5_se4_12.c.o: ../_5_tree/_5_4_12_util.h
CMakeFiles/ch5_s4_12.dir/_5_tree/_ch5_se4_12.c.o: ../_5_tree/_ch5_se4_12.c

