# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch5_s2_5.dir/_5_tree/_ch5_se2_5.c.o: ../_5_tree/SqBiTree.h
CMakeFiles/ch5_s2_5.dir/_5_tree/_ch5_se2_5.c.o: ../_5_tree/_ch5_se2_5.c

