# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch3_s2_3.dir/_3_stack_and_queue/queue/_ch3_se2_3.c.o: ../_3_stack_and_queue/queue/_ch3_se2_3.c
CMakeFiles/ch3_s2_3.dir/_3_stack_and_queue/queue/_ch3_se2_3.c.o: ../_3_stack_and_queue/queue/problem_common.h

