# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/han1254/Downloads/clion-2020.2.5/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/han1254/Downloads/clion-2020.2.5/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/han1254/Documents/PGEE/clion_datastructure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/ch3_s2_2.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/ch3_s2_2.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/ch3_s2_2.dir/flags.make

CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o: CMakeFiles/ch3_s2_2.dir/flags.make
CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o: ../_3_stack_and_queue/queue/_ch3_se2_2.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o   -c /home/han1254/Documents/PGEE/clion_datastructure/_3_stack_and_queue/queue/_ch3_se2_2.c

CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/han1254/Documents/PGEE/clion_datastructure/_3_stack_and_queue/queue/_ch3_se2_2.c > CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.i

CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/han1254/Documents/PGEE/clion_datastructure/_3_stack_and_queue/queue/_ch3_se2_2.c -o CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.s

# Object files for target ch3_s2_2
ch3_s2_2_OBJECTS = \
"CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o"

# External object files for target ch3_s2_2
ch3_s2_2_EXTERNAL_OBJECTS =

ch3_s2_2: CMakeFiles/ch3_s2_2.dir/_3_stack_and_queue/queue/_ch3_se2_2.c.o
ch3_s2_2: CMakeFiles/ch3_s2_2.dir/build.make
ch3_s2_2: CMakeFiles/ch3_s2_2.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable ch3_s2_2"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/ch3_s2_2.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/ch3_s2_2.dir/build: ch3_s2_2

.PHONY : CMakeFiles/ch3_s2_2.dir/build

CMakeFiles/ch3_s2_2.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/ch3_s2_2.dir/cmake_clean.cmake
.PHONY : CMakeFiles/ch3_s2_2.dir/clean

CMakeFiles/ch3_s2_2.dir/depend:
	cd /home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/han1254/Documents/PGEE/clion_datastructure /home/han1254/Documents/PGEE/clion_datastructure /home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug /home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug /home/han1254/Documents/PGEE/clion_datastructure/cmake-build-debug/CMakeFiles/ch3_s2_2.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/ch3_s2_2.dir/depend

