# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/clion_datastructure.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStack.h
CMakeFiles/clion_datastructure.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStackImpl.h
CMakeFiles/clion_datastructure.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStackMain.c
CMakeFiles/clion_datastructure.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/stack_common.h

CMakeFiles/clion_datastructure.dir/main.c.o: ../main.c

