# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/link_stack_main.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStack.h
CMakeFiles/link_stack_main.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStackImpl.h
CMakeFiles/link_stack_main.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/LinkStackMain.c
CMakeFiles/link_stack_main.dir/_3_stack_and_queue/stack/LinkStackMain.c.o: ../_3_stack_and_queue/stack/stack_common.h

