# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/sq_queue_main.dir/_3_stack_and_queue/queue/SqQueueMain.c.o: ../_3_stack_and_queue/queue/SqQueue.h
CMakeFiles/sq_queue_main.dir/_3_stack_and_queue/queue/SqQueueMain.c.o: ../_3_stack_and_queue/queue/SqQueueImpl.h
CMakeFiles/sq_queue_main.dir/_3_stack_and_queue/queue/SqQueueMain.c.o: ../_3_stack_and_queue/queue/SqQueueMain.c

