# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/parent_match.dir/_3_stack_and_queue/application/parentheses_match.c.o: ../_3_stack_and_queue/application/common_header.h
CMakeFiles/parent_match.dir/_3_stack_and_queue/application/parentheses_match.c.o: ../_3_stack_and_queue/application/parentheses_match.c

