# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/tree_main.dir/_5_tree/BiTreeMain.c.o: ../_5_tree/BiTree.h
CMakeFiles/tree_main.dir/_5_tree/BiTreeMain.c.o: ../_5_tree/BiTreeImpl.h
CMakeFiles/tree_main.dir/_5_tree/BiTreeMain.c.o: ../_5_tree/BiTreeMain.c
CMakeFiles/tree_main.dir/_5_tree/BiTreeMain.c.o: ../_5_tree/BiTreeQueueImpl.h
CMakeFiles/tree_main.dir/_5_tree/BiTreeMain.c.o: ../_5_tree/BiTreeStackImpl.h

