# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch5_s4_7.dir/_5_tree/_ch5_se4_7.c.o: ../_5_tree/BiTree.h
CMakeFiles/ch5_s4_7.dir/_5_tree/_ch5_se4_7.c.o: ../_5_tree/BiTreeImpl.h
CMakeFiles/ch5_s4_7.dir/_5_tree/_ch5_se4_7.c.o: ../_5_tree/BiTreeQueueImpl.h
CMakeFiles/ch5_s4_7.dir/_5_tree/_ch5_se4_7.c.o: ../_5_tree/BiTreeStackImpl.h
CMakeFiles/ch5_s4_7.dir/_5_tree/_ch5_se4_7.c.o: ../_5_tree/_ch5_se4_7.c

