# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/expression_change.dir/_3_stack_and_queue/application/expression_change.c.o: ../_3_stack_and_queue/application/common_header.h
CMakeFiles/expression_change.dir/_3_stack_and_queue/application/expression_change.c.o: ../_3_stack_and_queue/application/expression_change.c

