# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/BiTree.h
CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/BiTreeImpl.h
CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/BiTreeQueueImpl.h
CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/BiTreeStackImpl.h
CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/_5_3_13_util.h
CMakeFiles/ch5_s3_13.dir/_5_tree/_ch5_se3_13.c.o: ../_5_tree/_ch5_se3_13.c

