# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/str_main.dir/_4_string/StrMain.c.o: ../_4_string/SString.h
CMakeFiles/str_main.dir/_4_string/StrMain.c.o: ../_4_string/StrMain.c

