//
// Created by han1254 on 5/14/21.
//

#ifndef CLION_DATASTRUCTURE_COMMON_STATUS_H
#define CLION_DATASTRUCTURE_COMMON_STATUS_H
#define INT_MAX 2147483647
#define INT_MIN (-INT_MAX - 1)
#endif //CLION_DATASTRUCTURE_COMMON_STATUS_H
